### ISSUE TITLE
BOSC Poster

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#109]
Plan is to submit a poster abstract for BOSC 2015 about planemo - I usually do this on Google Docs but Github seems to be the trendy new way to do this abstract thing.

**Comment by bgruening** [comment]
:+1: what needs to be done?

**Comment by jmchilton** [comment]
@bgruening We need to turn a command-line utility into an exciting story worthy of a poster. Anything in particular you would like to talk about? I'm gathering thoughts now and I'll post a rough draft by the end of the day Wednesday - it is due Friday.

@erasche Are you going to be a co-author? If yes, can we write up something about your adventures with the tool shed and jenkins? I would be happy to throw something together about that in a first draft.

@kellrott There seems to be some publicly available information about the [top secret project anyway](https://github.com/kellrott/galaxy-tooldev-docs/blob/master/docs/06_Submitting.md) - so I would be happy add a short writeup to the abstract if you have any interest in being a co-author. No pressure though - if things should remain under wraps for now or if you would prefer not to be involved we will be fine.

**Comment by erasche** [comment]
@jmchilton would be happy to, I can contribute whatever and however you'd like :) I've been meaning to publicise what goes on behind the scenes with IUC testing anyway. If you sketch a really rough outline of what you want, I'd be happy to flesh it out fully with details and academic adjectives.

(/me pokes @bgruening for https://github.com/galaxyproject/tools-iuc/pull/74)

**Comment by ddooley** [comment]
Just a short note that I look forward to meeting you all if you are going to BOSC in Dublin!  Cheers,
  
 Damion
  

----------------------------------------

**Comment by kellrott** [comment]
@jmchilton It's not top secret ( https://www.synapse.org/#!Synapse:syn2813581 and on the front page of http://synapse.org and http://dreamchallenges.org/). Just still under getting ready to launch. Sure, if you want to talk about the construction of the SDK for the challenge, that would probably be a good thing.

**Comment by bgruening** [comment]
@jmchilton maybe you will find some ideas in the following.

* Planemo: Galaxy tool development and testing made easy.
* Improve usability for Galaxy tool developers with the Planemo project.

Galaxy has gained over time a very adoptive system to describe tools. This system is capable of integrating the most complex tools into the Galaxy framework, yet it can be as simple as writing a few lines in a markup language to make simple tools accessible. Today the Galaxy Tool Shed contains ~3000 tools from different areas of computational research and a vibrant community is updating and improving these tools. 
Nevertheless, a highly flexible system can implement the same feature in several ways and can get complicated very fast. A community based commission (IUC) is maintaining a best practice guide [[1](https://galaxy-iuc-standards.readthedocs.org/en/latest/),[2](https://wiki.galaxyproject.org/Tools/BestPractices)] to tackle the first problem and define high quality standards for Galaxy Tools. Planemo is a command-line utility that aims to solve the complexity problem and can help a Galaxy Tool developer to stick to best-practice guidelines. The Planemo project is closely working with the IUC to adopt to recent changes, integrate new features to stay in sync with the Galaxy project and to make Tool development simple. 

-------------

Continues testing of tools is a very important way to ensure the high quality of produced Galaxy tools. Unfortunately, this was not simple and probably the most complicated part in tool development.  Planemo closes this gap by automatizing testing steps completely and offering convenient tools to spot errors immediately, generating and visualizing error reports. These can be used by individual developers as well as in continuous integration testing with TravisCI or Jenkins to test tools as soon as they are pushed into a repository. 

Overall Planemo will drastically improve the quality of tools, both from a developer point of view as from the  Galaxy user (by unify Interfaces).

----
The Galaxy project is constantly facing the challenge to improve accessibility and usability. This problem is hard on it's own but it makes it even harder if you have a diverse user base like the Galaxy community has. User's can be found in any community, from wet-lab scientists to programmers and shell lovers. One group is interested in working with a web interface to analyze data, the others are more interested to deploy their tools or talk to Galaxy via an API. Here we present the Planemo project that can enhance the usability of Galaxy in general by assisting tool developers with a command-line utility to create high-class Galaxy tools. This will lower the barrier for developers to integrate their tools into Galaxy and  increase usability for all other users by sticking and providing best practices, resulting in more unified interfaces.

[1] https://galaxy-iuc-standards.readthedocs.org/en/latest/
[2] https://wiki.galaxyproject.org/Tools/BestPractices

**Comment by jmchilton** [comment]
Just to make this more complicated @martenson is now planning on submitting a Tool Shed abstract (people really want to go Dublin I think).

... maybe we should put the Jenkins stuff into that abstract (any objections @erasche). 
... maybe we should just make the rest planemo a paragraph in that abstract and I could do a workflow/collections abstract.

Hmm...

**Comment by erasche** [comment]
No objections, happy to go with the flow here.

**Comment by martenson** [comment]
I started the TS abstract here: https://docs.google.com/document/d/1bRQ1YzHc-DpIkiLAbYWHq-SBDs314x6prDpcm77s4mY/edit?usp=sharing and shared with @erasche directly

This is my first abstract, I don't have a good grasp on how to approach it so any help is more than welcomed.

**Comment by jmchilton** [comment]
@martenson and I talked some more - I think we are in agreement we should do a combined abstract on the tool shed and planemo - with him as first author. I am now planning on submitting a [separate abstract](https://docs.google.com/document/d/18iraqp-0ztfnsWCD_i9XqO07nBC3Mravp5b2NSrmlPc/edit?usp=sharing) on new collections developments and the new workflow plugin system.

**Comment by bgruening** [comment]
I see we have a real problem here - we have to many awesome projects!

**Comment by jmchilton** [comment]
@bgruening Indeed :).

**Comment by martenson** [comment]
Abstract seems in a decent shape to me, the abstract noob.
I would like to submit it on Friday before noon. Let me know if you want to work on it more so we can adjust.
Thanks all!

**Comment by jmchilton** [comment]
I needed to trim a lot back to make room for a description of SMC-Het and to add Kyle (@kellrott) to the author. I did most of this by trimming down the planemo section (I also rewrote it to make it more specific) and cutting back some on the first paragraph. I also dropped myself as an explicit author - this works for me because we ("The Galaxy Team") are pretty consistent on this I think - I was told not to add Nate or Carl to my abstracts last year.

The new link is here

https://docs.google.com/document/d/1O6mY05tSbRkqByvWFGiyA6rWDnje58NmCJHm1yKj1i0/edit?usp=sharing

@martenson is out visiting tourist sites in Washington DC so I am going to submit this for him in a half hour. Object now.

Also ping @nekrut

**Comment by erasche** [comment]
Objections noted. +1 from me.

**Comment by dannon** [comment]
Made a pass, mostly wording tweaks.  Looks good to me, now!

**Comment by jmchilton** [comment]
@dannon & @erasche Thanks for the attention to detail! All the edits were awesome - this reads a lot better to me now.

I wish it were my abstract we were submitting and not @martenson's but I warned him it was a mistake to let me submit it :). I will buy him a beer or several in Dublin.

**Comment by jmchilton** [comment]
Abstract submitted - closing the issue. Thanks all!

Looking forward to seeing everyone who will be there in Dublin!
