### ISSUE TITLE
shed_mirror command

### ISSUE THREAD

**Issue by erasche** [galaxyproject/planemo#119]
It would be nice to have a "shed_mirror" command that would take:

- source TS
- destination TS
- destination TS `--owner`
- a list of `username/package_name`

It would be a combination of `shed_download` and `shed_upload` with a temporary `tar xvfz; rm package*/.hg_archival.txt; tar cvfz;` in between.

Or...galaxy could just allow cross TS deps. `:|`

**Comment by martenson** [comment]
Galaxy aim is to not support multiple/custom Tool Sheds. The solution should be 'private' repositories on MTS instead.

**Comment by jmchilton** [comment]
I am less skeptical than @martenson - I am a pragmatist and will take any improvement over the current best practice workflows. But I do think it is hard to know how much effort to put into clearly helpful stop gaps like this - versus a more radical overhaul of dependencies (e.g. https://github.com/galaxyproject/planemo/issues/19) that would make stuff like cross TS dependencies kind of trivial.

**Comment by bgruening** [comment]
Cross TS dependencies will yield in many problems I imagine. Let's put this on the end of all ToDo lists ;)

**Comment by peterjc** [comment]
One major problem for this ``shed_mirror`` command is what to do with the hg revision entries in any dependency XML files?

A naive download from TS1 and upload to TS2 would break because the hg commit hashes used in dependencies in TS1 are unlikely to match those in TS2. Removing the revisions would result in using the latest version of the dependency in TS2, sometimes the right thing to do but not always.

(I think the Tool Shed needs to stop using hg commits as the dependency versioning string to make this and inter-toolshed dependencies possible)
