### ISSUE TITLE
some tool tags unknown to planemo lint

### ISSUE THREAD

**Issue by martenson** [galaxyproject/planemo#132]
```
samtools_mpileup.xml
Applying linter lint_xml_ordering... CHECK
.. INFO: Unknown tag [configfiles] encoutered, this may result in a warning in the future.
```
planemo complains about 'configfiles' tag in tool wrappers being unknown

it is listed as valid tag here: https://wiki.galaxyproject.org/Admin/Tools/ToolConfigSyntax#A.3Cconfigfiles.3E_tag_set

**Comment by peterjc** [comment]
I'd not spotted this until now due to typically running at the warning level only, but another missing tag:

```
Unknown tag [parallelism] encoutered, this may result in a warning in the future.
```

e.g. many of https://github.com/peterjc/galaxy_blast/tree/master/tools/ncbi_blast_plus and https://github.com/peterjc/pico_galaxy/tree/master/tools/protein_analysis use this tag, which I have been putting near the start between ``description`` and ``requirements``.
