### ISSUE TITLE
Collect and Use Git Revision

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#170]
Use commit ``git rev-parse HEAD`` + ``if `git diff --quiet` then '-dirty' else ''`` to capture git information at ``shed_upload``. At first use this information in the commit message to HG, but longer term we should collect the data on the tool shed in a more semantically useful way.

See also #169.

**Comment by peterjc** [comment]
Are any of the Galaxy community using ``hg`` for tool development? If so, adding something similar for mercurial hashes would be nice.

Also, thinking out loud, I'd like a safety feature to stop me from trying to upload uncommitted changes to the ToolShed. i.e. rather than adding "dirty" message (which is useful), should we prompt the user for confirmation? Or abort unless a ``--force`` flag is used? (following the ``git`` command line conventions, maybe not the best idea).

**Comment by jmchilton** [comment]
I would happily merge a PR to add ``hg`` support - but I don't intend to spend time on it personally. I think tool development is moving to Github and it would seem like wasted effort. I think we want to *actively* encourage Github specifically and short of that git more generally.

I like the spirit of the second idea a lot. For convenience and backward compatibility - my preference would be to invert the default (disallow ``-dirty`` commits with a flag - like ``--no_dirty`` - though that particular flag seems poorly named) and document how to modify the default with ``~/.planemo.yml``.
