### ISSUE TITLE
Kitematic (Need Help)

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#238]
The planemo machine docs should be updated with kitamatic instructions.

 - [x] Maybe screenshots of getting to booting the planemo image - https://registry.hub.docker.com/u/planemo/box/.
 - [x] Question: The Dockerfile ends with /bin/bash at the end of ``CMD`` so running ``docker run`` yields a shell after supervisor starts up. Does kitematic provide an interface for this or do kitmatic users need to SSH in or use the web ide?

I cannot get kitematic or boot2docker running on my Windows dev server - so help with this would be most welcome.

**Comment by erasche** [comment]
Answer to question (c/p from IRC), you can't get a shell like you do in normal docker from the CLI, however you can click "Exec" and launch a terminal. Almost as good.

**Comment by erasche** [comment]
For kitematic, it'd really work better to switch the second part of `CMD` to `tail -f /var/log...` just for the visual response for users.

**Comment by erasche** [comment]
Trimming images + uploading shortly.

**Comment by erasche** [comment]
![0-launch-kitematic](https://cloud.githubusercontent.com/assets/458683/8384505/050eb474-1c07-11e5-8fce-010453d3a3da.PNG)
![1-booting-kitematic](https://cloud.githubusercontent.com/assets/458683/8384506/05114a2c-1c07-11e5-9ec8-e41859bdfc76.PNG)
![2-finding-planemo](https://cloud.githubusercontent.com/assets/458683/8384509/0521caf0-1c07-11e5-8887-8ae8975c46da.PNG)
![4-downloading planemo](https://cloud.githubusercontent.com/assets/458683/8384511/0522e796-1c07-11e5-9082-2ee82c10255a.png)
![5-starting-planemo](https://cloud.githubusercontent.com/assets/458683/8384510/0522a024-1c07-11e5-9832-1505de4539f8.PNG)

You may want red circles around "Exec" and the link-out button above the galaxy screenshot
![6-planemo-running](https://cloud.githubusercontent.com/assets/458683/8384512/05252948-1c07-11e5-9f15-c3c0aba5ba99.PNG)
![7-powershell-root](https://cloud.githubusercontent.com/assets/458683/8384508/0520f0e4-1c07-11e5-9e85-ce46af1ea796.PNG)
![8-powershell-user](https://cloud.githubusercontent.com/assets/458683/8384507/051dbece-1c07-11e5-8407-83fa5bb11087.PNG)

**Comment by jmchilton** [comment]
Planemo's Dockerhub home now has separate 'server/kitematic' and 'interactive' versions of the planemo appliance and I registered a gravatar. https://hub.docker.com/u/planemo/

**Comment by jmchilton** [comment]
Closing out this issue - but if someone wanted to update the documentation with new screenshots reflecting switch to ``planemo/server`` as target box - I would buy this person a beer in Norwich :smile:.

**Comment by erasche** [comment]
@jmchilton excellent, love the interactive/server versions.

**Comment by erasche** [comment]
Commenting with more pictures because this is the easiest way to transfer pictures from fraking windows to my linux box sitting next to me. `:|`

![8-powershell-user](https://cloud.githubusercontent.com/assets/458683/8415762/c79050b4-1e66-11e5-8581-fda0f037a9eb.PNG)
![7-powershell-root](https://cloud.githubusercontent.com/assets/458683/8415764/c7a2350e-1e66-11e5-8993-0d22c37f46a9.PNG)
![6-planemo-running](https://cloud.githubusercontent.com/assets/458683/8415763/c7a0e2e4-1e66-11e5-8fdd-10b8e58dc94a.PNG)
![5-starting-planemo](https://cloud.githubusercontent.com/assets/458683/8415768/c7a77442-1e66-11e5-8d63-5f6776757edb.PNG)
![4-downloading planemo](https://cloud.githubusercontent.com/assets/458683/8415765/c7a3eb1a-1e66-11e5-9d7f-8e4bda0bbfdd.png)
![2-finding-planemo](https://cloud.githubusercontent.com/assets/458683/8415767/c7a7409e-1e66-11e5-8c71-1ff984ce2957.PNG)
![1-booting-kitematic](https://cloud.githubusercontent.com/assets/458683/8415766/c7a684ce-1e66-11e5-80cc-e402c2be679f.PNG)
![0-launch-kitematic](https://cloud.githubusercontent.com/assets/458683/8415769/c7af30ba-1e66-11e5-8e80-5db90369b114.PNG)

Excuse the dupes, I can't get a stupid HP support window to go away, so I can't easily see which pictures have changed. OH HOW 
![argh](https://cloud.githubusercontent.com/assets/458683/8415790/e7dfed5c-1e66-11e5-9094-8e3e617f1c24.PNG)
I HATE WINDOWS.

**Comment by martenson** [comment]
@erasche Can we please do this for Win Me too? Some trainees might use it.

**Comment by erasche** [comment]
Windows ME? As in [Windows Millenium Edition](https://en.wikipedia.org/wiki/Windows_ME)?

**Comment by martenson** [comment]
@erasche Yeah, I have heard the dialogues look very different and our trainees might get confused by the Win7 versions. I am already working on backporting the images to Win 3.11

**Comment by erasche** [comment]
@martenson hahahaha ohh I need to stop taking everyone so seriously ...

**Comment by erasche** [comment]
thanks for the laugh
