### ISSUE TITLE
Multiple install directories for planemo dependency_script?

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/planemo#320]
The initial `planemo dependency_script` implementation f798c7e (see #303 and #310) produces a single `dep_install.sh` and `env.sh` script even when called on multiple `tool_dependencies.xml` files. The simplistic usage model is to run `bash dep_install.sh` and `source env.sh` prior to running Galaxy or any Galaxy tests.

Issue #319 addresses where to put a separate `env.sh` scripts for each tool under the `tool_dependency_dir` folder set in `galaxy.ini` or via `planemo test --tool_dependency_dir <dep_dir> ...`

This issue is about a similar approach for where to put the files created by the installation itself, i.e. automatically adjusting the `$INSTALL_DIR` for multiple `tool_dependencies.xml` files. This would allow co-installation of clashing filenames (e.g. multiple versions of MIRA or BLAST).

Motivating example https://github.com/peterjc/galaxy_mira/commit/0d41761e7073f8fac4c9a4b2a34a95e839ef76f1 and https://travis-ci.org/peterjc/galaxy_mira/builds/84351148 - in this case `planemo dependency_script` is used on three `tool_dependencies.xml` files to install three versions of MIRA. The clashing binary name `mira` requires installation into separate folders and has implications for determining priority on `$PATH` (which would be addressed by #319). The workaround as shown is to call `planemo dependency_script` three times in a particular order.

**Comment by peterjc** [comment]
According to https://wiki.galaxyproject.org/Admin/Config/ToolDependencies if we put binaries under e.g. ``<dep_dir>/MIRA/3.4.1.1/bin/`` then they will automatically be detected by Galaxy and added to ``$PATH`` if a tool XML declares a dependency using:

```
<requirement type="package" version="3.4.1.1">MIRA</requirement>
```

Many ``tool_dependencies.xml`` files do simply download and compile/uncompress binaries and move them to ``$INSTALL_DIR``. So perhaps it would make sense to ``<dep_dir>/<name>/<version>/bin/`` as an option for where the bash script should put things?

**Comment by bgruening** [comment]
Not sure if this helps but you could also create `<dep_dir>/MIRA/default` as a symlink to a specific folder with an `env.sh` file or a `bin/`.
Otherwise I think `<dep_dir>/MIRA/3.4.1.1/bin/` is a good idea.

**Comment by peterjc** [comment]
See also this nice blog post from Peter Van Heusden http://pvh.wp.sanbi.ac.za/2015/10/09/how-galaxy-resolves-dependencies-or-not/ which talks about the default symlink mentioned by @bgruening

**Comment by peterjc** [comment]
In testing ``planemo dependency_script`` on https://github.com/peterjc/pico_galaxy the dependencies are failing for https://github.com/peterjc/pico_galaxy/tree/master/tools/clinod and https://github.com/peterjc/pico_galaxy/tree/master/tools/effectiveT3 which I traced to the assumption in their ``tool_dependencies.xml`` files that the current directory *is* ``$INSTALL_DIR``:

```xml
<actions>
    <!-- Set environment variable $CLINOD so wrapper knows where to look -->
    <action type="set_environment">
        <environment_variable name="CLINOD" action="set_to">$INSTALL_DIR</environment_variable>
    </action>
    <!-- clinod requires the SNNS Batch Interpreter v1.0 executable -->
    <action type="shell_command">wget http://www.ra.cs.uni-tuebingen.de/downloads/SNNS/SNNSv4.3.tar.gz</action>
    <action type="shell_command">tar -zxvf SNNSv4.3.tar.gz</action>
    <action type="move_file"><source>SNNSv4.3/tools/bin/x86_64-pc-unknown-linux-gnuoldld/batchman</source><destination>$INSTALL_DIR/</destination></action>
    <!-- clinod itself is just a JAR file -->
    <action type="shell_command">wget http://www.compbio.dundee.ac.uk/nod/downloads/clinod-1.3.jar</action>
    <!-- Don't need to move it, $INSTALL_DIR is the current directory
    <action type="move_file"><source>clinod-1.3.jar</source><destination>$INSTALL_DIR</destination></action>
    -->
 </actions>
```

Currently the ``dep_install.sh`` script produced from this is:

```bash
#!/bin/bash
#set -euo pipefail
set -eo pipefail
if [[ ! -d $INSTALL_DIR ]]
then
    echo "ERROR: Environment variable INSTALL_DIR not a directory!"
    exit 1
fi
# Set full strict mode now, side stepping case $INSTALL_DIR not setup.
set -euo pipefail
export DOWNLOAD_CACHE=`(cd "$DOWNLOAD_CACHE"; pwd)`
if [[ ! -d $DOWNLOAD_CACHE ]]
then
    mkdir -p $DOWNLOAD_CACHE
fi
echo "Using $DOWNLOAD_CACHE for cached downloads."
export INSTALL_DIR=`(cd "$INSTALL_DIR"; pwd)`
echo "Using $INSTALL_DIR for the installed files."
# Create a randomly named temp folder for working in
dep_install_tmp=${TMPDIR-/tmp}/dep_install.$RANDOM.$RANDOM.$RANDOM.$$
(umask 077 && mkdir $dep_install_tmp) || exit 1
echo "============================================================"
echo "Installing clinod version 1.3"
echo "============================================================"
specifc_action_done=0
cd $dep_install_tmp
#------------------------------------------------------------
if [[ $specifc_action_done == 0 ]]
then
    echo "Non-platform-specific actions"
    export CLINOD=$INSTALL_DIR
    wget http://www.ra.cs.uni-tuebingen.de/downloads/SNNS/SNNSv4.3.tar.gz
    tar -zxvf SNNSv4.3.tar.gz
    mv SNNSv4.3/tools/bin/x86_64-pc-unknown-linux-gnuoldld/batchman $INSTALL_DIR/
    wget http://www.compbio.dundee.ac.uk/nod/downloads/clinod-1.3.jar
fi
echo "Cleaning up..."
rm -rf $dep_install_tmp
echo "======================"
echo "Installation complete."
echo "======================"
```

By deliberately creating a randomly named temporary working directory this means that in this case while the binary ``batchman`` is moved into ``$INSTALL_DIR``, the jar file ``clinod-1.3.jar`` is left in the temporary folder.

Likewise, for ``effectiveT3``,

```xml
<actions>
    <!-- Set environment variable so Python script knows where to look -->
    <action type="set_environment">
        <environment_variable name="EFFECTIVET3" action="set_to">$INSTALL_DIR</environment_variable>
    </action>
    <!-- Main JAR file -->
    <action type="shell_command">wget http://effectors.csb.univie.ac.at/sites/eff/files/others/TTSS_GUI-1.0.1.jar</action>
    <!-- If using action type download_file will need to move the file,
    <action type="move_file"><source>TTSS_GUI-1.0.1.jar</source><destination>$INSTALL_DIR/</destination></action>
    -->
    <!-- Three model JAR files -->
    <action type="make_directory">$INSTALL_DIR/module</action>
    <action type="shell_command">wget http://effectors.csb.univie.ac.at/sites/eff/files/others/TTSS_ANIMAL-1.0.1.jar</action>
    <action type="move_file"><source>TTSS_ANIMAL-1.0.1.jar</source><destination>$INSTALL_DIR/module/</destination></action>        
    <action type="shell_command">wget http://effectors.csb.univie.ac.at/sites/eff/files/others/TTSS_PLANT-1.0.1.jar</action>
    <action type="move_file"><source>TTSS_PLANT-1.0.1.jar</source><destination>$INSTALL_DIR/module/</destination></action>
    <action type="shell_command">wget http://effectors.csb.univie.ac.at/sites/eff/files/others/TTSS_STD-1.0.1.jar</action>
    <action type="move_file"><source>TTSS_STD-1.0.1.jar</source><destination>$INSTALL_DIR/module/</destination></action>
    <action type="shell_command">wget http://effectors.csb.univie.ac.at/sites/eff/files/others/TTSS_STD-2.0.2.jar</action>
    <action type="move_file"><source>TTSS_STD-2.0.2.jar</source><destination>$INSTALL_DIR/module/</destination></action>
</actions>
```

giving:

```bash
...
echo "============================================================"
echo "Installing effectiveT3 version 1.0.1"
echo "============================================================"
specifc_action_done=0
cd $dep_install_tmp
#------------------------------------------------------------
if [[ $specifc_action_done == 0 ]]
then
    echo "Non-platform-specific actions"
    export EFFECTIVET3=$INSTALL_DIR
    wget http://effectors.csb.univie.ac.at/sites/eff/files/others/TTSS_GUI-1.0.1.jar
    mkdir -p $INSTALL_DIR/module
    wget http://effectors.csb.univie.ac.at/sites/eff/files/others/TTSS_ANIMAL-1.0.1.jar
    mv TTSS_ANIMAL-1.0.1.jar $INSTALL_DIR/module/
    wget http://effectors.csb.univie.ac.at/sites/eff/files/others/TTSS_PLANT-1.0.1.jar
    mv TTSS_PLANT-1.0.1.jar $INSTALL_DIR/module/
    wget http://effectors.csb.univie.ac.at/sites/eff/files/others/TTSS_STD-1.0.1.jar
    mv TTSS_STD-1.0.1.jar $INSTALL_DIR/module/
    wget http://effectors.csb.univie.ac.at/sites/eff/files/others/TTSS_STD-2.0.2.jar
    mv TTSS_STD-2.0.2.jar $INSTALL_DIR/module/
fi
echo "Cleaning up..."
rm -rf $dep_install_tmp
echo "======================"
echo "Installation complete."
echo "======================"
```

Here the four modules are explicitly moved into ``$INSTALL_DIR/module`` but the master JAR file ``TTSS_GUI-1.0.1.jar`` is assumed to be at ``$INSTALL_DIR/TTSS_GUI-1.0.1.jar`` but is currently left in the temporary working folder.

Judging from my comments in the XML, I was surprised that when ``tool_dependencies.xml`` is executed by the Tool Shed installation ``$INSTALL_DIR`` is the current working directory. I would have thought a temporary working folder would make more sense (no reason to keep temporary files generated during compilation for example). Evidently I was still thinking this when writing the ``planemo dependency_script`` command.

It seems the ``planemo dependency_script`` output needs to include a ``cd $INSTALL_DIR`` line and abandon my temporary working directory approach for full compatibility with existing ``tool_dependencies.xml`` files? Given this, as per the original goal of this issue, we ought to use a separate ``$INSTALL_DIR`` for each ``tool_dependencies.xml`` file.

**Comment by jmchilton** [comment]
@peterjc just a quick glance through the code this is surprising, it does seem to be trying to use a different working directory - something may be undoing that somewhere though...

https://github.com/galaxyproject/galaxy/blob/dev/lib/tool_shed/galaxy_install/install_manager.py#L62
https://github.com/galaxyproject/galaxy/blob/dev/lib/tool_shed/galaxy_install/tool_dependencies/recipe/install_environment.py#L257
https://github.com/galaxyproject/galaxy/blob/dev/lib/tool_shed/galaxy_install/tool_dependencies/recipe/install_environment.py#L164

**Comment by peterjc** [comment]
Thanks @jmchilton - the Galaxy Tool Shed  install code you've highlighted certainly does suggest a temporary working directory is intended rather than ``$INSTALL_DIR``.

@gregvonkuster -  Is it possible that my ``clinod`` and ``effectiveT3`` and perhaps other ``tool_dependencies.xml`` files ought to fail as written? Maybe they do, its been a while since I tested them & the Tool Shed no longer does this for us.

**Comment by gregvonkuster** [comment]
@peterjc Its a bit difficult for me to say for sure what should or should not currently work for recipes as I believe there have been several changes (since the original installation code was written) that may affect installations.  The original intent was to not use $INSTALL_DIR for the software download and compile steps, but rather to move compiled files to that directory as a final step of the installation recipe.  

The installation process automatically creates a temporary working directory in which the downloads are placed when using the download_by_url and download_file actions.  In the past this temporary working directory was not readily accessible within recipes, but I recently added support for using a new $TMP_WORK_DIR reserved word in ways similar to the use of $INSTALL_DIR.  This reserved word points to the temporary working directory root for us within the download and compile steps.  This allows for cleaner installations for more complex recipes that may install more than a single package (e.g., install Python and then install bumpy into that Python).  An example of a recipe that uses this approach is here:

https://github.com/gregvonkuster/galaxy-csg/blob/master/packages/package_icqsol_latest/tool_dependencies.xml

**Comment by peterjc** [comment]
@gregvonkuster I agree it would be better if ``$TMP_WORK_DIR != $INSTALL_DIR``, but it sounds like sometimes ``$TMP_WORK_DIR == $INSTALL_DIR``. My hunch is this may depend on the actions used - especially what the first action is?

Note both these examples start with a ``set_environment`` action and avoid using the ``download_file`` action (my old comments suggest I was hacking this treating the install mechanism as something of a black box, the are likely not following "best practise").

**Comment by gregvonkuster** [comment]
@peterjc I don't believe $TMP_WORK_DIR could ever be the same as $INSTALL_DIR in the original implementation, and I don't think changes since then have affected this behavior (but I could be wrong).  The set_environment_for_install actions only set environment paths in preparation for compiling the current package, and I don't think either $TMP_WORK_DIR nor $INSTALL_DIR is affected or used for this action.  I think the only actions that download source or binary files are still download_by_url and download_file, and the installation framework automatically creates a temporary working directory for both of these actions.  That temporary working directory is not the same as $INSTALL_DIR.  This temporary working directory can be referred to with the recently supported $TMP_WORK_DIR.

However, if you are using wget inside of a shell_command action, this behavior is not used (i.e., a temporary working directory is not automatically created for you, and you cannot use $TMP_WORK_DIR.  In the original implementation, we could not assume that wget or curl were available in the Galaxy environment.

**Comment by peterjc** [comment]
OK, so some actions for download will create and change to a temp working directory (available as ``$TMP_WORK_DIR``).

If those action are not used (e.g. just using ``wget`` etc inside of a ``shell_command``), then ``$TMP_WORK_DIR`` does not get created. Would the default current working directory be? Is it as I suspect ``$INSTALL_DIR``?

**Comment by gregvonkuster** [comment]
@peterjc Yes, $INSTALL_DIR always gets created and can be accessed in recipes using that reserved word.  So in those cases that you are using wget inside of a shell_command action, your "working directory" may very well be the same as $INSTALL_DIR.

**Comment by gregvonkuster** [comment]
@peterjc I think I should clarify my above statement where I said:

"However, if you are using wget inside of a shell_command action, this behavior is not used (i.e., a temporary working directory is not automatically created for you, and you cannot use $TMP_WORK_DIR)."

Actually, like $INSTALL_DIR, $TMP_WORK_DIR is always created since all actions happen within this block:
https://github.com/galaxyproject/galaxy/blob/dev/lib/tool_shed/galaxy_install/install_manager.py#L62

What I meant to say was referring to $TMP_WORK_DIR within the contents of a shell_command action may or may not work as expected.

Another point I should make is in the initial implementation all actions were confined to be within a location under the temporary working directory $TMP_WORK_DIR.  This provided security in that it did not allow doing malicious things outside of this temporary work space.  So, for example, you could not change directory to $INSTALL_DIR.  I'm not sure if or how this may impact your implementation.

**Comment by peterjc** [comment]
@gregvonkuster let's discuss this path oddity on https://github.com/galaxyproject/galaxy/issues/896 instead?

**Comment by erasche** [comment]
Same as https://github.com/galaxyproject/planemo/pull/321
