### ISSUE TITLE
Conda Recipe

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#402]
- [ ] Start a channel for Galaxy project.
 - [x] Distribute planemo via conda.

**Comment by bgruening** [comment]
John I have reserved a IUC channel, afaik. But I'm currently not clear if we want this or if we join bioconda completely. Happy to discuss this anytime soon.

**Comment by jmchilton** [comment]
Cool - I'll happily reuse whatever you decide.

**Comment by bgruening** [comment]
It's worth to use bioconda but we need to convince them to put a little bit more effort in sustainability. We have an IUC channel and I plan to use this was hacky tools or old/archaic backports to not pollute bioconda.

However planemo is a devtool and it fits perfectly to bioconda: https://github.com/bioconda/bioconda-recipes/pull/966

Hope this is useful for you!

P.S. Before you ask, cwltool is not a dependency because sparqlwrapper has a circular dependency on rdflib. I have some initial work here but this is currently unresolvable. I will work on this an other day. For the time being I hope you don't mind to leave this out of the conda package. Sorry this is not intentional, I actually spend quite some time on it.
