### ISSUE TITLE
planemo conda_install issue

### ISSUE THREAD

**Issue by lecorguille** [galaxyproject/planemo#433]
Hi,

Some of my tools need the brand new conda package [bioconductor-camera](https://bioconda.github.io/recipes/bioconductor-camera/README.html)
```xml
    <requirements>
        <requirement type="package" version="1.22.0">bioconductor-camera</requirement>
    </requirements>

```

It can be install without trouble: `conda install bioconductor-camera`

But when I use `planemo conda_install .` to build an env (if I understand well), I get this:
```bash
Linking packages ...
Error: ERROR: placeholder '/root/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placehold_p' too short in: ncurses-5.9-4
```

The full path of this uncomplete env is `/home/lecorguille/miniconda2/envs/__package__bioconductor-camera@__version__1.22.0`

I looked around and find those threads without understand which path or filename is too long:
https://github.com/rtfd/readthedocs.org/issues/1902
https://github.com/conda/conda/issues/1087

Any idea?

**Comment by yguitton** [comment]
Sorry, Never heard of that conda dependency, it is not listed in CAMERA dependencies "http://bioconductor.org/packages/release/bioc/html/CAMERA.html"

**Comment by lecorguille** [comment]
@yguitton It's a R dependency: https://github.com/conda/conda-recipes/blob/master/r-base/meta.yaml

But it seem to come from my setups (CentOS and Ubuntu). Because travis test pass on travis-ci.org when I use `planemo conda_install ${TRAVIS_BUILD_DIR}/galaxy/xcms_suite ` (https://github.com/workflow4metabolomics/xcms/blob/master/.travis.yml)

So if you (planemo developers) are considering that it's not link to a planemo issue. I can hear that.

**Comment by mvdbeek** [comment]
It isn't really a planemo issue, the problem is that long link paths are problematic with conda.
So a workaround is to make sure that the directory path where planemo bootstraps galaxy is pretty short.
On OSX, by default $TMPDIR would be something like /var/folders/56/g35vb5h14_v0d6chwtfxvdfr0000gn/T/  and then mkdtemp() would give you a path like /var/folders/56/g35vb5h14_v0d6chwtfxvdfr0000gn/T/ tmpi35zzj which exceeds the limit (since in addition the is a path structure where the conda dependencies are linked to) and you get the error mentioned in the opening post.
At least on OSX I can work around the issue with PR #460

**Comment by lecorguille** [comment]
By default planemo install miniconda2 in the home directory and then conda install environments and packages in some subfolders
Finally, I solve this problem using `planemo conda_init --conda_prefix /tmp/mc` and `planemo conda_install --conda_prefix /tmp/mc .`

But I didn't test yet on a "real" Galaxy instance on our HPC. We will need to find a better/shorter path then the Galaxy home directory.
