### ISSUE TITLE
planemo test hangs with empty <test></test>

### ISSUE THREAD

**Issue by dwightkuo** [galaxyproject/planemo#586]
planemo test does not complete successfully if there is no test between <test></test>:

i.e.

```
<tests>
   <test>
   </test>
</tests>
```

**Comment by peterjc** [comment]
That sounds like a bug - I would expect ``planemo test`` to report this as a failed test.

(And ``planemo lint`` should report this as an error)

**Comment by jmchilton** [comment]
I think this is because the underlying tool hangs without an input - this seems like a tool wrapper issue to me? This seems like a valid test to some degree - run the tool with default inputs and make sure it passes. Feel free to reopen if I'm wrong and tests always fail if specified like this. There is an open linter issue to do a better job about reporting output assertions.
