### ISSUE TITLE
Travis is broken with 0.40?

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#659]
I have no clue why...

xref https://github.com/galaxyproject/tools-iuc/pull/1209/files#r107214879

**Comment by jmchilton** [comment]
Potentially related is this https://travis-ci.org/galaxyproject/tools-iuc/jobs/212955891 from https://github.com/galaxyproject/tools-iuc/pull/1207 as well.

**Comment by peterjc** [comment]
I think it likely depends on how planemo is being used under TravisCI, these all worked with planemo 0.40.0 (triggered via the new TravisCI cron job feature rather than any code change on my side):

https://travis-ci.org/peterjc/galaxy_blast/jobs/213046919
https://travis-ci.org/peterjc/pico_galaxy/jobs/213047835
https://travis-ci.org/peterjc/galaxy_mira/jobs/213046948

Note these all setup Galaxy on their own (because I explicitly want to check both the master and dev branches, and in some cases also install datatypes), rather than letting planemo do that for me.

**Comment by bgruening** [comment]
Sorry, to be late to the game. I have seen this as well, but the few minutes I spend in it I could not find it.

**Comment by bgruening** [comment]
I think this is fixed. We are using latest planemo and latest Galaxy, everything seems to work.

**Comment by jmchilton** [comment]
This was bizarre - I never even developed a theory for what was wrong. Well I'm glad a newer setup is working - thanks for confirming that @bgruening!
