### ISSUE TITLE
Directory of a dataset collection

### ISSUE THREAD

**Issue by Mataivic** [galaxyproject/planemo#676]
Hello,

I am currently writing a wrapper for orthofinder (https://github.com/davidemms/OrthoFinder) and I encountered a problem. I gathered my input data in a dataset collection and the orthofinder command writes each file of the dataset instead of their directory, like this :
orthofinder -f file1.fasta,file2.fasta,file3.fasta,file4.fasta ... Instead of
orthofinder -f files_directory/ , which the required typo.

How can I obtain the path or the directory name of the dataset collection ? Below is a short overview of my code (only the concerned part)

```
`<command>
<![CDATA[		
	#set $infiles = ""
        #for $input in $inputs
            ln -s $input $input.element_identifier;
            #set $infiles = $infiles + $input.element_identifier + ","
        #end for
        #set $infiles = $infiles[:-1]        	
		
	orthofinder -f $infiles
]]>
</command>`
```
The 'inputs' parameter is :
`<param name="inputs" type="data" multiple="true" label="Choose input files" />`

I hope it's clear.

Thank you !

**Comment by gregvonkuster** [comment]
@Mataivic I have defined several new PlantTribes-based Galaxy datatypes that handle these directories of files.  They are in this PR https://github.com/galaxyproject/galaxy/pull/3999 to which I will be committing another small addition today.  I believe the ```ptortho``` datatype defined here https://github.com/galaxyproject/galaxy/pull/3999/files#diff-d5c80b3279bf41b0a8f1368025c840c7L606 may be the one that you could use with your tool.

The tools I'm developing are here https://github.com/gregvonkuster/galaxy_tools/tree/master/tools/plant_tribes, and they use these new datatypes.  They are not written to produce and consume dataset collections since the directories of files produced by the tools consist of multiple datatypes and, in some cases, multiple levels of directories of files.  The datatypes are subclassed from the HTML datatypes, so the primary dataset renders the directory of files, each of which is clickable.  The datatypes cannot be uploaded (using the upload form) in case that matters.

It might be good to see if these datatypes will work for your tools so that we can define a standard approach for these kinds of tools.  Please let me know if you have any questions about this.

**Comment by Mataivic** [comment]
@gregvonkuster I figured it out finally, : thanks to the --no_cleanup option of planemo, I have found that the files of the dataset are in the working directory : I just had to write :
`orthofinder -f .`
I can't believe it took me hours to understand that.
