### ISSUE TITLE
Explore Incremental Continuous Integration Testing

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#7]
It might be a larger amount of effort than anything else in this project - but it would be cool. See conversation at https://github.com/galaxyproject/tools-devteam/issues/10.

**Comment by jmchilton** [comment]
It looks like Homebrew/science does something like this using TRAVIS_COMMIT and Homebrew `brew-bot` command (e.g. https://github.com/Homebrew/homebrew-science/pull/1679). Places to look if pursuing this.

**Comment by peterjc** [comment]
Revisiting this issue with some numbers from using TravisCI on large tool repositories: If we want to continue to use automated testing like TravisCI with large multi-tool repositories, then we need to have some sort of selective testing based on the recent git history (ideally spot changes since the last test run, and test any potentially affected tool).

The devteam and IUC have a couple of large GitHub repositories containing dozens of individual Galaxy tools or tool collections, as do I:

* https://github.com/galaxyproject/tools-iuc
* https://github.com/galaxyproject/tools-devteam
* https://github.com/peterjc/pico_galaxy

Even the BLAST+ collection maps to several Tool Shed entries, and the main collection now has many tools in it:

* https://github.com/peterjc/galaxy_blast

As previously noted, these big repositories have advantages like being easy for new tool developers to search for usage patterns.

As you know I've been using TravisCI to run continuous integration functional testing of my Galaxy tools, but this works better with shorter test runs.  Currently galaxy_blast takes about 30 minutes
per target (including about 1 minute downloading and setting things up), while pico_galaxy takes about 40 minutes (including a larger set of dependencies to download and setup):

* https://travis-ci.org/peterjc/galaxy_blast/builds
* https://travis-ci.org/peterjc/pico_galaxy/builds

It is possible to test multiple targets in parallel (eg Python 2.6 vs 2.7, and Galaxy dev vs master branch), but four targets per build seems greedy with these long run times.

As an experiment yesterday I split out the MIRA wrappers from pico_galaxy into their own repository - TravisCI testing of this takes about 8 minutes per target (about 2 minutes of which is downloading and setting up planemo, Galaxy, and three versions of MIRA):

https://github.com/peterjc/galaxy_mira
https://travis-ci.org/peterjc/galaxy_mira/builds

[As an aside I have tried using "planemo test" here but there are some teething issues, e.g.
https://github.com/galaxyproject/planemo/issues/291 ]

Purely in terms of more immediate feedback from TravisCI, splitting up larger repositories like pico_galaxy seems like a worthwhile effort.

**Note that while the ratio depends on the tools and tests, setting up planemo and the Galaxy instance is a small fraction of the run times in these examples.**

In the absence of incremental testing, it is tempting to split things up even more so that one Tool Shed repository maps to a single GitHub repository, at which point the setup overhead (downloading and installing planemo, galaxy, and the tool dependencies) may be much more noticeable.

**Comment by mvdbeek** [comment]
I have a kind-of-working incremental continuous integration setup with jenkins.
Basically I got a local toolshed server with all the tools and packages I wish to test.
Upon each push to our repo jenkins triggers linting, and upon sucesfull linting triggers a shed_upload.
I then take *only* the updated repositories and run a shed_test on them. It works quite well
and picks up problems with the tool dependencies as well as the tools themselves.
@erasche recently picked this up in https://github.com/galaxy-iuc/jenkins-testing
Perhaps this could be more tightly integrated with planemo?

**Comment by peterjc** [comment]
@mvdbeek interesting - I could imaging reworking my TravisCI system to use a persistent external Tool Shed (e.g. Test Tool Shed) as the mechanism to spot updated tools (e.g. via ``planemo shed_diff``) and only test those. And I do like the idea of automating pushes to the Test Tool Shed. In this setting having coupled tools/dependencies/datatypes in the same GitHub repository should be an advantage (pushing updates to datatype/dependencies should mean a change to the dependent tool, and thus trigger a retest).

Note that unlike the typical TravisCI model, if a commit broke a tool you'd only see the failure once - subsequent builds would not retest the broken tool (unless it was subsequently updated).

**Comment by mvdbeek** [comment]
@peterjc Yes, that's indeed the downside of the model. I could imagine a functionality
to test only updated tools, plus tools that are currently broken (useful in case a tool
produces inconsistent test results). Which would work alright if only a few tools are broken,
else we're back to square 1.

Maybe worth mentioning, the code I'm using does spark parallel tests with --cores > 1,
but that's not a very elegant workaround. I don't know if you can use multiple processes in travis though.

**Comment by erasche** [comment]
@peterjc excellent post, thanks for sharing your experiences.

Here's my grand plan.

For the development side

- I find time to get @mvdbeek's contributions plugged in the appropriate places in planemo/jenkins/etc and we use the new Jenkins instance being deployed by @martenson to do selective testing of only things which have changed based on git commits, and hopefully provide this as a service to users and groups. My ideal, current version of this involves:
  - lint all the things (as a separate job)
  - check what has changed since the last test of master (assuming a feature branch model)
  - for all of those differences build up the complete dependency tree
  - launch a private docker toolshed
  - fetch missing dependencies from the main toolshed
  - install packages/tools/etc in the correct ordering according to our dependency tree
  - stand up a galaxy, install tools, test them

@mvdbeek sorry I haven't had more time to work with your contributions. I really appreciate them, it's just been very busy lately.

For the "production" side:

- I wrap up the toolshed I'm working on in secret
  - this will remove the "fetch missing dependencies from the MTS" step
- We implement CI integration with that, you get your testing back and feedback on that end from releases with a nice little green badge saying that tests have passed.

**Comment by peterjc** [comment]
I've got a rough version of incremental testing & automated deployment running on TravisCI, the idea being that I run ``planemo shed_diff`` to decide which tools have changed in git, and call ``planemo test`` on those only. Finally if the tests pass, I call ``planemo shed_update`` on those working updated tests:

https://travis-ci.org/peterjc/galaxy_mira/jobs/80332785

The key idea here (based on @mvdbeek's idea) is rather than looking over the recent git commits to deduce what has changed, I am using the (Test) Tool Shed as an external persistent archive.

There are wrinkles like how to balance a TravisCI build matrix with this - currently I only do the ``planemo shed_update`` for the final build target.

Also the way the information is presented in TravisCI needs some polish - but then ``planemo test`` itself is very verbose to the terminal.

**Comment by peterjc** [comment]
An example of the dangers of just testing changed tools, https://travis-ci.org/peterjc/pico_galaxy/builds/80425694 failed because the upstream website broke the tool download URLs - https://github.com/peterjc/pico_galaxy/issues/9

i.e. Any continuous integration testing of changed tools only would need to be supplemented by periodic testing of the full suite.

**Comment by erasche** [comment]
@peterjc the alternative I'd envision is testing the diff vs master for PRs and then testing master on merge.
