### ISSUE TITLE
Suggestion of publish command

### ISSUE THREAD

**Issue by erasche** [galaxyproject/planemo#82]
Since the publish instructions look long and unpleasant, you might consider a [publish command](https://github.com/erasche/galaxyxml/blob/master/setup.py#L5) like I've implemented. Except fancier and supporting the [entire checklist](http://planemo.readthedocs.org/en/latest/developing.html#release-checklist) for planemo. Just a suggestion, feel free to close the issue, just wanted to document it on official channels rather than doing something like tweeting it.

**Comment by bgruening** [comment]
+1

**Comment by jmchilton** [comment]
I have updated the release process notes (fba38746e7bbfbc227f64249a089e539460a7bb1) and I think it is more automated now - including the following the ``Makefile`` commands (instead of addressing things at the ``setup.py`` level):

```
dist: clean
	python setup.py sdist bdist_egg bdist_wheel
	ls -l dist

release-test: dist
	twine upload -r test dist/*
	echo "Review https://testpypi.python.org/pypi/planemo"

release:
	@while [ -z "$$CONTINUE" ]; do \
		read -r -p "Have you executed release-test and reviewed results? [y/N]: " CONTINUE; \
	done ; \
	[ $$CONTINUE = "y" ] || [ $$CONTINUE = "Y" ] || (echo "Exiting."; exit 1;)
	@echo "Releasing"
	twine upload dist/*
```

Let me know if you have specific ideas for further automation - I think a lot of the individual steps is because there is a human review check in there. It would be nice to automate tests of the the released artifacts to test PyPI for instance - but that should be a new issue I guess.
