### ISSUE TITLE
having trouble using shed_upload

### ISSUE THREAD

**Issue by martenson** [galaxyproject/planemo#87]
it seems to be using OSX system Python instead of venv's (which I think is the correct brew way) but still fails
```
$ which python
/Users/marten/devel/venv/base/bin/python
```

```python
$ planemo shed_upload --message "testing planemo upload" --shed_target testtoolshed
Traceback (most recent call last):
  File "/usr/local/Cellar/planemo/0.5.0/libexec/bin/planemo", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: markupsafe
```

**Comment by martenson** [comment]
```
$deactivate
$sudo easy_install -U pip
$sudo pip install markupsafe
```
all running

**Comment by bwlang** [comment]
For me - using the python from home brew (/usr/local/bin/python)
I had to do this to get planemo working:
sudo /usr/bin/easy_install -U pip
(which overwrote my homebrew pip... grr)
then
sudo /usr/bin/pip install markupsafe
brew reinstall python (to replace pip)

I think it would be better for planemo to use the python that is on the path than /usr/bin/python...

**Comment by jmchilton** [comment]
@bwlang - Thanks for the bug report on missing markupsafe - that was entirely a bug on my part. It should be fixed with https://github.com/galaxyproject/homebrew-tap/commit/8b0d6e294034172449e5469ead0d5048fab00a86.

It stinks that an updated version of pip is required for the install - but I am just following the pattern of the ansible recipe (https://github.com/Homebrew/homebrew/blob/master/Library/Formula/ansible.rb) which is the most comparable piece of software that I could think of. Would it have been possible to upgrade the version of pip required with homebrew instead of ``easy_install``?

Planemo certainly can use whatever Python you want if you install it with ``pip install planemo`` or ``python setup.py install`` - but advice on improving the Homebrew recipe is appreciated.
