### ISSUE TITLE
Testing composite output files has a few issues

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/planemo#878]
Composite datatypes are getting more important as more communities trying to use Galaxy. We have discovered that given the following code the tests with planemo are not running as expected.
 
```
<output name="outfile_imzml" file="filtering_imzmls/summary" compare="sim_size" delta="10000">
   <extra_files type="file" name="imzml" value="filtering_imzmls/out4.imzML" compare="sim_size" delta="10000"/>
   <extra_files type="file" name="ibd" value="filtering_imzmls/out4.ibd" compare="sim_size" delta="10000"/>
</output>
```

* sim_size on the level of extra_files do not seem to have any effect
* `--update_test_data` does not work with those tests
* a failing test does not indicate what the error is, e.g. the `diff` or the `delta`

**Comment by jmchilton** [comment]
It works in unit testing 😅 - https://github.com/galaxyproject/galaxy/pull/14661/commits/e06960ce16d72ccd2e3b929b7eb0b75fcba0f696.

Obviously unit tests are not integration tests - something might get lost when it is all working together - but the code is there and there is some chance this was fixed in our tool testing overhauls a couple years ago. We did a lot of work at that time.

**Comment by bgruening** [comment]
I think this works now. I have seen a few tools in galaxyp using it in the last years. Thanks!
